### ISSUE TITLE
README acronyms are ambiguous

### ISSUE THREAD

**Issue by CoolCat467** [CompArchCam/optiwise#4]
I happened to see this project come up in my dashboard feed, and being curious about it I read the readme, and I was confused about what some of the acronyms used mean. Is `CPI` "Clicks Per Index" and `IPC` "Inter Process Control"? I feel like it is unclear what exactly this project does at first glance just from reading the readme, and not using ambiguous acronyms would be a helpful step for alleviating that.

**Comment by Chadderz121** [comment]
Thanks for the comment, I've made the first paragraph of the README a little more verbose. We'll probably add more proper examples as we approach the 1.0.0 release.

In this context, IPC and CPI are referring to Instructions per Cycle and Cycles per Instruction, two metrics which are simply the inverse of each other. A cycle here refers to a clock cycle of the processor, so for example a 2GHz processor nominally has 2 billion clocks cycles per second. Typical high performance processors these days can in principle execute multiple instructions per cycle on a single core, commonly 4 to 8 IPC per core. However, in practice we often get considerably less than this amount in real programs, and this tool is designed to help one determine where the IPC is taking a hit in a real program. In practice what we often see is that things like some branch instructions and some memory load and store instructions take considerably longer, and this tool outputs the average CPI of each instruction in the program allowing one to see which instructions are taking longer than the expected amount so that the program can be optimised.

Hopefully that clarifies!

**Comment by CoolCat467** [comment]
Thank you so much for the clarification, that makes a lot of sense. I definitely think this would be a useful tool for profiling and optimizing; I get that the name is a pun now haha! Being smart about optimizing because you have actual data to work with instead of guessing what's slowing the program down.

Thank you for the information, have a great day!
